services:
  - type: web
    name: infinity-gamers
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: ADMIN_USER
        value: Infinitygamers001
      - key: ADMIN_PASS
        value: Infinitygamers@8
